#+TITLE: 因子投资方法与实践 -- 笔记与代码
#+AUTHOR: 胡琛

* 因子投资基础

* 因子投资方法论
#+BEGIN_QUOTE
首先介绍如何使用排序法构建因子模拟组合并检验，它是一切的基础。
然后是使用不同的回归方法对多因子模型进行检验，这是核心。
之后进一步对因子暴露和因子收益率检验进行解读，因子投资中一个重要内容就是通过异象获取多因子模型无法解释的超额收益。
再然后是介绍不同的多因子模型方法。
跟着是多因子处理方式：1. 因子正交化 2. 广义矩估计
#+END_QUOTE

** 因子组合排序法
如何定量描述解释股票收益率的因子，需要用到实证资产定价和因子投资中一个重要的概念--因子模拟投资组合。
*** 因子模拟投资组合
1. 因子模拟投资组合是使用股票资产，围绕某个目标因子构建的投资组合
2. 投资组合需要满足以下条件
   - 该投资组合仅在目标因子上有大于 0 的暴露，在其他因子暴露为 0
   - 在所有满足条件一的投资组合中，该投资组合的特质性风险最小
3. 举例：下表中可以构建的围绕因子 A, 符合投资组合条件的组合可以是股票一与股票四等权重配置
   | 股票   | 因子A 暴露 | 因子 B 暴露 | 特质性风险 |
   |--------+------------+-------------+------------|
   | 股票一 |        0.8 |         0.4 |         1% |
   | 股票二 |        1.3 |         0.6 |         2% |
   | 股票三 |        0.6 |        -0.4 |         5% |
   | 股票四 |        1.2 |        -0.4 |         1% |
*** 排序法及其检验
构建因子的模拟组合前提是知道所有股票在该因子上的暴露，股票在某因子上 $i$ 上的暴露 $\beta_i$ 反映的是在
控制其他因子后，该目标因子的收益率变化对股票超额收益变化的影响程度。这意味着需要首先知道因子收益率才能计算
因子暴露。但是，之前讨论是需要有因子模拟组合后才能计算因子收益，因子暴露又是构建因子模拟组合的前提，由此，
构建因子模拟组合陷入矛盾。一种绕过矛盾的方案是通过排序法来构建因子组合。

以账面市值比(BM, book-to-market ratio, 市净率倒数)为例
1. 排序：首先确定股票池，将池中所有股票在截面上按照排序变量的取值高低从大到小 (或从小到大) 排序
2. 分组：按排序高低将全部股票分为 L 组 (按照惯例，一般取十分位)。最多排名最高的第一组股票，做空排名最低
   的最后一组股票，由此构建一个多空对冲的组合，该投资组合又被称为 **价差组合**。
3. 定期更新：个股在变量上并非取值不变，需要定期进行上述两个步骤，学术上称之为 **再平衡** ，一般再平衡的
   频率为一个月或一年。
上述检验方法称之为 **投资组合排序检验**

投资组合排序检验最重要的目的是检验因子预期收益率。理论上，因子预期收益率应该大于 0 (否则按照多因子模型，
对资产定价，该因子为 0，没有意义)，因此，检验关注的是根据样本数据计算出来的因子收益率，能否在给定的显著性
水平下拒绝因子收益率为 0 的假设。

令 $\{\lambda_t\}(t=1,2,\ldots,T)$ 表示因子收益率时间序列，则因子预期收益率的估计 $\hat{\lambda}$
以及其标准误差 $s.e.(\hat{\lambda})$ 分别为
\begin{aligned}
  \hat{\lambda} &= \frac{1}{T}\sum\limits_{t=1}^T\lambda_t\\
  s.e.(\hat{\lambda}) &= \frac{\mathbf{std}(\lambda_t)}{\sqrt{T}}
\end{aligned}
有了 $\hat{\lambda}$ 与 $s.e.(\hat{\lambda})$, 便可以在原假设 ($\lambda=0$) 进行 t-检验，计算 t-值。
\begin{equation}
  t = \frac{\hat{\lambda}}{s.e.(\hat{\lambda})}
\end{equation}
上式满足自由度为 $T-1$ 的 t 分布。根据 t-值和 t-分布 可以计算出 p 值，然后通过 t-value 和 p-value 就
能够在给定的显著性水平下接受或拒绝原假设。

以 BM 为例对全 A 股市场进行检验，检验采用截面方法，对应 09-30 的财务日期，取 06-30 的截面数据[fn:1][fn:2]
#+BEGIN_SRC python
import QUANTAXIS as QA

# 全市场股票代码
code_list_1 = QA.QA_fetch_stock_list().index.tolist()

# 上市时间过滤
data = QA.QA_fetch_stock_day_adv(code=code_list, start="2010-01-01", end="2020-09-30")
#+END_SRC

** 多因子模型的回归检验
** 因子暴露与因子收益率
** 异象检验
** 多因子模型比较
** 因子正交化
** 广义矩阵分析
** 研究方法建议

* Footnotes

[fn:2] 考虑到数据获取难易与收费情况，这里主要使用两个数据源，quantaxis(通达信的数据) 和掘金量化

[fn:1] 譬如，在 2020-09-30 对应的日期，上一期财报原则上都应该公布了，此时，在 09-30 这个截面上，取 06-30 的
财务数据，是比较合理的选择
